[package]
name = "tensort"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tch = "0.15.0"

[dev-dependencies]
assertables = "7.0.1"
tempfile = "3.10.1"

[[bin]]
name = "tensort"
path = "src/main.rs"